export const confirmationStyles = {
  container: {
    width: 'min(90vw, 400px)',
    background: 'var(--admin-card)',
    color: 'var(--admin-text-primary)',
    padding: 'clamp(1rem, 3vw, 1.75rem)',
    borderRadius: 'var(--admin-radius)',
    border: '1px solid var(--admin-border)',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    backdropFilter: 'blur(12px)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  iconWrapper: {
    padding: '0.6rem',
    background: 'rgba(var(--admin-brand-rgb), 0.1)',
    borderRadius: 'var(--admin-radius-sm)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid rgba(var(--admin-brand-rgb), 0.2)',
  },
  title: {
    margin: 0,
    fontWeight: '950',
    fontSize: '0.95rem',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    lineHeight: '1.2',
  },
  message: {
    margin: '0.2rem 0 0 0',
    fontSize: '0.8rem',
    color: 'var(--admin-text-secondary)',
    fontWeight: '600',
    opacity: 0.8,
  },
  buttonContainer: {
    display: 'flex',
    gap: '0.75rem',
    marginTop: '0.5rem',
  },
  buttonBase: {
    flex: 1,
    padding: '0.85rem',
    borderRadius: 'var(--admin-radius-sm)',
    fontSize: '0.75rem',
    fontWeight: '950',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  confirmButton: {
    background: 'var(--admin-brand)',
    color: '#FFFFFF',
    boxShadow: '0 4px 12px rgba(169, 27, 24, 0.2)',
  },
  cancelButton: {
    background: 'var(--admin-bg)',
    color: 'var(--admin-text-secondary)',
    border: '1px solid var(--admin-border)',
  }
};
